name: Telegram Sinyal Botu

on:
  schedule:
    # Her saat başı çalışır (UTC zaman diliminde)
    - cron: '0 * * * 1-5'  # Pazartesi-Cuma her saat başı
  workflow_dispatch:  # Manuel çalıştırma seçeneği

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest

    steps:
      # Depoyu klonlama
      - name: Depoyu klonla
        uses: actions/checkout@v4

      # Python ortamını kurma
      - name: Python ortamını kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Bağımlılıkları yükleme
      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Telegram botunu çalıştırma
      - name: Telegram botunu çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # Türkiye saatiyle 10:00-18:00 kontrolü
          CURRENT_HOUR=$(date -u +%H)
          # UTC'den Türkiye saatine (UTC+3) geçiş
          TR_HOUR=$((CURRENT_HOUR + 3))
          if [ $TR_HOUR -ge 10 ] && [ $TR_HOUR -lt 18 ]; then
            echo "Türkiye saatiyle 10:00-18:00 aralığında, bot çalışıyor..."
            python Telegram.py
          else
            echo "Türkiye saatiyle 10:00-18:00 dışında, bot çalıştırılmadı."
          fi
